services:
  postgres:
    image: postgres:15-alpine
    container_name: acta-solution-postgres
    restart: always
    environment:
      POSTGRES_USER: acta_solution_user
      POSTGRES_PASSWORD: acta_solution_password
      POSTGRES_DB: acta_solution_db
    ports:
      - '5432:5432'
    volumes:
      - acta_solution_db_data:/var/lib/postgresql/data

volumes:
  acta_solution_db_data:
